project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel Ansah"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: Curriculum Vitae (CV).qmd
        text: "{{< fa user-tie >}} Curriculum Vitae (CV)"
        
    right:
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

