project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel Ansah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Curriculum Vitae (CV).qmd
        text: Curriculum Vitae (CV)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

